// hands-on-design.test.js
// Auto-generated by genRootFrameTest.js based on design-tokens.json
// Do not edit manually, regenerate if design tokens change.

import { render, screen } from '@testing-library/react';
import HandsOnDesign from '../components/HandsOnDesign';

describe('HandsOnDesign Component', () => {
  it('should have the correct Tailwind classes based on design tokens', () => {
    render(<HandsOnDesign />);
    const rootElement = screen.getByTestId('hands-on-design');

    expect(rootElement).toBeInTheDocument();

    // Verify Tailwind classes using arbitrary values
    expect(rootElement).toHaveClass('flex', 'flex-col', 'justify-between', 'items-center', 'gap-[10px]', 'pt-[10px]', 'pb-[10px]', 'pl-[10px]', 'pr-[10px]', 'w-screen', 'h-screen', 'overflow-hidden', 'bg-[#3ade63]');

    // Optionally, add tests for children structure or specific attributes if needed
  });
});
