// Hero.test.js
// Auto-generated by genLayoutFrameTest.js for hands-on-design/Hero based on design-tokens.json
// Do not edit manually, regenerate if design tokens change.

import { render, screen } from '@testing-library/react';
// Assuming the layout component is rendered within its parent (e.g., the root component)
// We might need to adjust the import if the component is standalone
// For now, let's assume we render the Root component and find the layout frame within it.
// TODO: Revisit this assumption based on actual component structure.
import HandsOnDesign from '../components/HandsOnDesign'; // Assuming root is HandsOnDesign

describe('Hero Layout Frame', () => {
  it('should render within the application and have correct Tailwind classes', () => {
    render(<HandsOnDesign />); // Render the root component
    const layoutElement = screen.getByTestId('Hero'); // Find the specific layout frame

    expect(layoutElement).toBeInTheDocument();

    // Verify Tailwind classes using arbitrary values
    // Note: Class comparison might be brittle if classes are dynamically added/removed.
    // Consider testing computed styles for more robustness if needed.
    expect(layoutElement).toHaveClass('flex', 'flex-row', 'justify-center', 'items-center', 'gap-[10px]', 'pt-[30px]', 'pb-[30px]', 'pl-[30px]', 'pr-[30px]', 'w-[373px]', 'h-[242px]');

    // Verify frame name is rendered inside
    expect(layoutElement).toHaveTextContent('Hero');

    // TODO: Add more specific tests? (e.g., children count, specific attributes)
  });
});
