// src/tests/gen-funcs/genLayoutFrameTest.js

const fs = require('fs');
const path = require('path');
const { getNameFromTokenKey } = require('../../utils/tokenUtils');
const {
    kebabToPascalCase,
    extractStylesFromTokens
} = require('../utils/testGenUtils');

/**
 * Generates Jest test code for a specific layout frame component based on design tokens.
 * Reads tokens from a JSON file and targets a specific frame key.
 * @param {string} designTokensPath - Path to the design tokens JSON file.
 * @param {string} frameKey - The specific key for the layout frame (e.g., "hands-on-design/Nav").
 * @returns {string} - The generated test code as a string.
 */
function genLayoutFrameTest(designTokensPath, frameKey) {
  try {
    // Read and parse the design tokens JSON file
    const designTokensRaw = fs.readFileSync(designTokensPath, 'utf8');
    const designTokens = JSON.parse(designTokensRaw);

    if (!designTokens[frameKey]) {
      throw new Error(`Frame key '${frameKey}' not found in the design tokens.`);
    }

    // Get component name using the utility from tokenUtils
    const kebabComponentName = getNameFromTokenKey(frameKey);
    const pascalComponentName = kebabToPascalCase(kebabComponentName);

    // Extract Tailwind classes using the utility from testGenUtils, isRoot = false
    const { tailwindClasses } = extractStylesFromTokens(designTokens, frameKey, false);
    const testId = kebabComponentName; // Use kebab-case name for test ID

    // Format Tailwind classes for the test assertion
    const formattedClasses = tailwindClasses.map(cls => `'${cls}'`).join(', ');

    // Generate the test file content
    // Assumes the component will be located in src/components/
    const testCode = `// ${kebabComponentName}.test.js
// Auto-generated by genLayoutFrameTest.js for ${frameKey} based on ${path.basename(designTokensPath)}
// Do not edit manually, regenerate if design tokens change.

import { render, screen } from '@testing-library/react';
// Assuming the layout component is rendered within its parent (e.g., the root component)
// We might need to adjust the import if the component is standalone
// For now, let's assume we render the Root component and find the layout frame within it.
// TODO: Revisit this assumption based on actual component structure.
import HandsOnDesign from '../components/HandsOnDesign'; // Assuming root is HandsOnDesign

describe('${pascalComponentName} Layout Frame', () => {
  it('should render within the application and have correct Tailwind classes', () => {
    render(<HandsOnDesign />); // Render the root component
    const layoutElement = screen.getByTestId('${testId}'); // Find the specific layout frame

    expect(layoutElement).toBeInTheDocument();

    // Verify Tailwind classes using arbitrary values
    // Note: Class comparison might be brittle if classes are dynamically added/removed.
    // Consider testing computed styles for more robustness if needed.
    expect(layoutElement).toHaveClass(${formattedClasses});

    // TODO: Add more specific tests? (e.g., children count, specific attributes)
  });
});
`;

    return testCode;

  } catch (error) {
    console.error(`Error generating test code for ${frameKey}:`, error);
    throw error; // Re-throw the error to indicate failure
  }
}

// Example Usage (modified to dynamically find frames)
if (require.main === module) {
  const tokensPath = path.join(__dirname, '..', '..', 'data', 'design-tokens.json');

  try {
    const designTokensRaw = fs.readFileSync(tokensPath, 'utf8');
    const designTokens = JSON.parse(designTokensRaw);

    // Find the root frame key (assuming it has no '/')
    const rootFrameKey = Object.keys(designTokens).find(key => !key.includes('/'));
    if (!rootFrameKey) {
      throw new Error('Could not find the root frame key in the design tokens.');
    }

    // Find all direct child frames (keys with exactly one '/')
    const layoutFrameKeys = Object.keys(designTokens).filter(key => {
        const parts = key.split('/');
        // Check if it starts with the root key and has exactly one '/' separator
        return key.startsWith(rootFrameKey + '/') && parts.length === 2;
    });

    if (layoutFrameKeys.length === 0) {
        console.warn('No layout frame keys found (e.g., root/child). Ensure your design tokens follow this structure.');
        process.exit(0);
    }

    console.log(`Found layout frames: ${layoutFrameKeys.join(', ')}`);

    layoutFrameKeys.forEach(frameKey => {
        try {
            const kebabName = getNameFromTokenKey(frameKey); // Gets the part after the last '/'
            const outputFileName = `${kebabName}.test.js`;
            const outputPath = path.join(__dirname, '..', outputFileName); // Output to src/tests/

            const generatedCode = genLayoutFrameTest(tokensPath, frameKey);
            fs.writeFileSync(outputPath, generatedCode);
            console.log(`Layout frame test file generated successfully for ${frameKey}: ${outputPath}`);
        } catch (generationError) {
            console.error(`Failed to generate test file for ${frameKey}: ${generationError.message}`);
            // Continue to the next key even if one fails
        }
    });

  } catch (error) {
    console.error(`Failed to process design tokens or generate layout frame tests: ${error.message}`);
    process.exit(1);
  }
}

module.exports = genLayoutFrameTest;
